### ISSUE TITLE
Not an issue - mandelbrot  

### ISSUE THREAD

**Issue by f41ardu** [mikebharris/COBOL-Brainfuck#1]
Works well, but incredible slow.

**Comment by adelaydeelsevier** [comment]
Hey f41ardu.  Any ideas for speeding it up?

**Comment by f41ardu** [comment]
No, I use a PI 4. But I have no time to make further investigations into brainfuck. But impressive that you built a Cobol version!!!! 
Did some more investigations from a, lets say philosophers point of view. Run brainfuck code in a brainfuck interpreter built in bf runing this interpreter in brainfuck interpreter in C. Mandelbrot.bf is challenging ;->

**Comment by adelaydeelsevier** [comment]
Thanks! Yeah I have the intention of trying to speed up the interpreter at some point.  If I get around to it and it works, I'll let you know. ;)
